### PR TITLE
Add rust example

### PR DESCRIPTION
**Pull request by r-marques**
Created an example in rust

### CODE REVIEW

**Comment by avinassh** [comment]
Thank you for the PR! Rust is not officially supported by gRPC. Can you also add setup instructions?

**Comment by r-marques** [comment]
This example uses the grpc-rs crate that is a wrapper for grpc.

I updated the instructions with some more information. In the end you only need rustup installed in your system and cmake in case grpc-rs needs to compile the grpc code.

The generation of the protobuf files is integrated into the cargo build process so `cargo run` should is the only necessary command to run the example.

**Comment by avinassh** [comment]
Thank you so much, I have merged it! 

Would you like to add a concise example on the home page? - http://avi.im/grpc-errors/

for this, you need to edit `README.md` on `gh-pages` branch - https://github.com/avinassh/grpc-errors/blob/gh-pages/README.md

**Comment by r-marques** [comment]
No problem. I will also create and example for the homepage and submit a pull request

**Pull request merged**
